version: '2'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - productos
            - clientes

        ports:
            - "8081:80"
              
    productos:
        build: ./productos

    clientes:
        build: ./clientes
